export const REST_ENDPOINTS = {
  AUTH: {
    USERNAME_VALIDATE: "/auth/username/validate",
    EMAIL_VALIDATE: "/auth/email/validate",
    PASSWORD_VALIDATE: "/auth/password/validate",
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    SESSION: "/auth/session",
    HANDSHAKE: "/auth/handshake",
  },
  POSTS: {
    BASE: "/posts",
    BY_ID: "/posts/:id",
    LIKE: "/posts/:id/like",
    UNLIKE: "/posts/:id/unlike",
    COMMENT: "/posts/:id/comment",
    COMMENTS: "/posts/:id/comments",
    POPULAR_COMMENTS: "/posts/:id/comments/popular",
    EDIT_COMMENT: "/posts/:postId/comments/:commentId",
    DELETE_COMMENT: "/posts/:postId/comments/:commentId",
    COMMENT_HAS_LIKED: "/posts/:postId/comments/:commentId/has-liked",
    COMMENT_LIKE_COUNT: "/posts/:postId/comments/:commentId/like-count",
    COMMENT_LIKE: "/posts/:postId/comments/:commentId/like",
    COMMENT_UNLIKE: "/posts/:postId/comments/:commentId/unlike",
    HAS_LIKED: "/posts/:id/has-liked",
    LIKE_COUNT: "/posts/:id/like-count",
    COMMENT_COUNT: "/posts/:id/comment-count",
    USER: "/posts/user",
    USER_POPULAR: "/posts/user/popular",
    POPULAR: "/posts/popular",
  },
  USERS: {
    SEARCH: "/users/search",
    SEARCH_FRIENDS: "/users/friends/search",
    FRIENDS: "/users/friends",
    FRIEND_REQUEST: "/users/friend-request/:id",
    FRIEND_REQUESTS: "/users/friend-requests",
    ACCEPT_FRIEND_REQUEST: "/users/accept-friend-request/:id",
    DENY_FRIEND_REQUEST: "/users/deny-friend-request/:id",
    REMOVE_FRIEND: "/users/remove-friend/:id",
    DETAILED_INFO: "/users/:id",
    ARE_FRIENDS: "/users/:id/are-friends",
    HAS_SENT_FRIEND_REQUEST: "/users/has-sent-friend-request/:id",
    HAS_RECEIVED_FRIEND_REQUEST: "/users/has-received-friend-request/:id",
    ACTIVITY: "/users/activity",
  },
  MESSAGES: {
    CREATE: "/messages/conversations/:id",
    CONVERSATION: "/messages/conversations/:id",
    CONVERSATIONS: "/messages/conversations",
    BY_ID: "/messages/:id",
    MARK_AS_READ: "/messages/read/:id",
    UNREAD_COUNT: "/messages/unread/count",
    CONVERSATION_ID_BY_FRIEND: "/messages/conversation-id/:id",
  },
  MATCH: {
    QUEUE: "/match/queue",
    CANCEL: "/match/cancel",
    GET_INFO: "/match/info",
    RUN: "/match/run",
  },
  SETTINGS: {
    GET_SETTINGS: "/settings",
    UPDATE_SETTINGS: "/settings",
    UPDATE_PROFILE_PICTURE: "/settings/pfp",
  },
  GLOBAL: {
    GET_STATS: "/global/stats",
    GET_GENERAL_STATS: "/global/general-stats",
    GET_TOP_RANKED_USERS: "/global/top-ranked-users",
  },
  APPLICATION: {
    BASE: "/application",
  },
};
